- hosts: all
  become: true
  vars:
  - install_directory: /opt/
    CTOP_VERSION: "0.7.3"
    DOCKER_COMPOSE_VERSION: "1.25.1"
    DOCKER_PACKAGES:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properies-common 
    USER: "smithalexanderbradley"    
  
  
  tasks:
    - name: Install Docker Requirements
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        state: latest
        update_cache: true


    - name: Add official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: latest
        update_cache: true
    
    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user to docker group  
      user:
        name: "{{ USER }}"
        groups: "docker"
        append: "yes"

    - name: Install Docker-Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: Install Ctop
      get_url:
        url: https://github.com/bcicen/ctop/releases/download/v{{ CTOP_VERSION }}/ctop-{{ CTOP_VERSION }}-linux-amd64
        dest: "/usr/local/bin/ctop"
        mode: 0755

    - name: Reboot server
      shell: "sleep 1 && reboot"
      async: 1
      poll: 0    


